---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: copy-bin-files
      copy:
        src: ../files/bin/
        dest: /root/code/bin/
        mode: '0755'
      tags: bin
    - name: add-bin-to-path
      copy:
        force: yes
        dest: /etc/profile.d/code-bin.sh
        content: 'PATH=$PATH:/root/code/bin'
      tags: bin
    - name: add-code-folder
      copy:
        force: yes
        src: ../files/code/
        dest: /root/code/
      tags: code
    - name: copy-ssl-certs
      copy:
        force: yes
        src: ../files/certs/
        dest: /etc/ssl/fluwide/
      tags: certs
#    - name: copy-ssl-certs
#      copy:
#        force: yes
#        src: ../files/certs/
#        dest: /etc/ssl/fluwide/
#        with_fileglob:
#          - ../files/certs/*.crt
#          - ../files/certs/*.pem
    - name: copy-nginx-default
      copy:
        force: yes
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
      tags: nginx
    - name: copy-nginx-sites-enabled
      copy:
        force: yes
        src: ../files/nginx-sites-enabled/
        dest: /etc/nginx/sites-enabled/
      tags:
        - nginx
