version: "3"

services:
  fluwide:
    image: jphuisman92/fluwide:latest
    restart: "no"
    ports:
      - "3000:3000"

  life:
    image: jphuisman92/jeroenlife:latest
    restart: "no"
    ports:
      - "4000:3000"

  credion:
    image: jphuisman92/credion:latest
    restart: "no"
    ports:
      - "3005:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://omgvamp-hearthstone-v1.p.rapidapi.com
      NEXT_PUBLIC_RAPID_API_KEY: 360d1d6c53mshe8d6253e672c364p11ab36jsnaa91ab9f6a2a
      NEXT_PUBLIC_RAPID_API_HOST: omgvamp-hearthstone-v1.p.rapidapi.com

  palate-redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  palate-db:
    image: postgres:16
    environment:
      POSTGRES_DB: &PG_DB palate
      POSTGRES_USER: &PG_USER postgres
      POSTGRES_PASSWORD: &PG_PASS password
    ports:
      - "3306:5432"
    stdin_open: true
    tty: true

  palate-api:
    &palate-api
    image: jphuisman92/palate:latest
    entrypoint: [""]
    restart: "no"
    command: pm runserver 0.0.0.0:9000
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    environment:
      UWSGI_PROCESSES: 4
      PYTHONUNBUFFERED: 1
      # Django and application settings
      DJANGO_SETTINGS_MODULE: palate.settings.dev
      SECRET_KEY: secret
      # Database
      DB_HOST: palate-db
      DB_NAME: *PG_DB
      DB_USER: *PG_USER
      DB_PASS: *PG_PASS
      DB_PORT: 5432
      # REDIS
      CELERY_RESULT_BACKEND: redis://palate-redis/0
      CELERY_BROKER_URL: redis://palate-redis/0
    env_file:
      - /root/code/.env.palate
    depends_on:
      - palate-db
      - palate-redis
    volumes:
      - ./backend:/app/code:z

  palate-worker:
    <<: *palate-api
    image: jphuisman92/palate:latest
    command: bash -c "run-worker.sh"
    ports:
      - "5001:9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/sites-enabled:/etc/nginx/conf.d/:rw
      - /etc/ssl/fluwide/:/etc/ssl/fluwide/:rw
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
