#!/bin/bash

# install docker on the machine
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt-cache policy docker-ce
sudo apt install -y docker-ce
sudo systemctl status docker

docker pull jphuisman92/fluwide:latest
docker run -p 3000:3000 -d jphuisman92/fluwide:latest

docker pull jphuisman92/jeroenlife:latest
docker run -p 4000:3000 -d jphuisman92/jeroenlife:latest