#!/bin/bash

# get absolute path of folder
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

droplet_ip=$(cat $DIR/../droplet_ip.txt)

function ssh_digitalocean {
  ssh -i ~/.ssh/digitalocean "root@${droplet_ip}"
}

ssh_digitalocean
